server:
  port: 8002

api :
  tinkoffConfig :
    tinkoffService : ${gcpTinkoffService}
    getStocksByTickers : /stocks/getStocksByTickers
    getPrices: /prices
  moexConfig:
    moexService: ${gcpMoexService}
    getStocksByTickers: /bonds/getBondsByTickers
    getPrices: /bonds/prices

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    root : INFO
  file:
    name: logs/StockService.log
